package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.AbstractC1080g;
import com.google.android.gms.common.api.InterfaceC1193k;
import com.google.android.gms.common.api.InterfaceC1194l;
import com.google.android.gms.common.api.Status;

/* JADX INFO: renamed from: com.google.android.gms.common.api.internal.bo */
/* JADX INFO: loaded from: classes.dex */
public final class C1127bo<R extends InterfaceC1193k> extends AbstractC1080g<R> {

    /* JADX INFO: renamed from: a */
    private final Status f5666a;

    @Override // com.google.android.gms.common.api.AbstractC1080g
    /* JADX INFO: renamed from: a */
    public final void mo6694a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC1080g
    /* JADX INFO: renamed from: a */
    public final void mo6695a(AbstractC1080g.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC1080g
    /* JADX INFO: renamed from: a */
    public final void mo6696a(InterfaceC1194l<? super R> interfaceC1194l) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC1080g
    /* JADX INFO: renamed from: b */
    public final boolean mo6697b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC1080g
    /* JADX INFO: renamed from: c */
    public final Integer mo6698c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* JADX INFO: renamed from: d */
    final Status m6893d() {
        return this.f5666a;
    }
}
